defaults:
  - polygraph_eval_triviaqa_default_instruct
  - top1_processing_triviaqa
  - default_blackbox_estimators
  - _self_

experiment_name: triviaqa_empirical_baselines

description: "Provide your best guess for the following question. Give ONLY the guess, no other words or explanation.\n\nFor example:\n\nGuess: <most likely guess, as short as possible; not a complete sentence, just the guess!>"
few_shot_prompt: "Question: {question}\nGuess: {answer}"
prompt: "Question: {question}\n"
max_new_tokens: 30
generation_params:
  generate_until:
    - "\n"

stat_calculators:
  - auto