defaults:
  - polygraph_eval_coqa_default_instruct
  - top1_processing_coqa
  - default_blackbox_estimators
  - _self_

experiment_name: coqa_empirical_baselines

dataset: ['LM-Polygraph/coqa', 'empirical_baselines']
description: "Here's a short story:\n\n{story} (End of story)\n\nProvide your best guess for the following question. Give ONLY the guess, no other words or explanation.\n\nFor example:\n\nGuess: <most likely guess, as short as possible; not a complete sentence, just the guess!>"
few_shot_prompt: "Question: {question}\nGuess: {answer}"
prompt: "Question: {question}\n"
max_new_tokens: 30
generation_params:
  stop_strings:
    - "\n"

stat_calculators:
  - auto
