defaults:
  - polygraph_eval_coqa_default_instruct
  - topk_processing
  - _self_

experiment_name: coqa_verb_2s_topk

topk: 4
description: "Here's a short story:\n\n{story} (End of story)\n\nProvide your ${topk} best guesses for the following question. Give ONLY the guesses, no other words or explanation. For example:\n\nG1: <first most likely guess, as short as possible; not a complete sentence, just the guess!>\n...\nG${topk}: <${topk}-th most likely guess, as short as possible; not a complete sentence, just the guess!>"
few_shot_prompt: "Question: {question}\nG1: {answer}\n...\nG${topk}: <other guess>"
prompt: "Question: {question}\n"
max_new_tokens: 125

additional_estimators: 
  - module: lm_polygraph.estimators.verbalized_2s
    class_name: Verbalized2S
    kwargs:
      confidence_prompt: "Provide the probability that each of your guesses is correct. Give ONLY the probabilities, no other words or explanation.\n\nFor example:\n\nP1: <the probability between 0.0 and 1.0 that G1 is correct, without any extra commentary whatsoever; just the probability!>\n...\nP${topk}: <the probability between 0.0 and 1.0 that G${topk} is correct, without any extra commentary whatsoever; just the probability!>"
      confidence_regex: 'P1: (\d+\.\d+)'
      max_new_tokens: 50
      name_postfix: "_topk"
