- name: MaximumSequenceProbability
- name: Perplexity
- name: MeanTokenEntropy
- name: MonteCarloSequenceEntropy
- name: MonteCarloNormalizedSequenceEntropy
- name: LexicalSimilarity
  cfg:
    metric: "rougeL"
- name: NumSemSets
- name: EigValLaplacian
  cfg:
    similarity_score: "NLI_score"
    affinity: "entail"
- name: DegMat
  cfg:
    similarity_score: "NLI_score"
    affinity: "entail"
- name: CDegMat
  cfg:
    similarity_score: "NLI_score"
    affinity: "entail"
- name: Eccentricity
  cfg:
    similarity_score: "NLI_score"
    affinity: "entail"
- name: CEccentricity
  cfg:
    similarity_score: "NLI_score"
    affinity: "entail"
- name: SemanticEntropy
  cfg:
    samples: "all"
    normalize: false
    estimator: "sample"
- name: SemanticEntropy
  cfg:
    samples: "all"
    normalize: false
    estimator: "direct"
- name: SemanticEntropy
  cfg:
    samples: "all"
    normalize: true 
    estimator: "sample"
- name: SemanticEntropy
  cfg:
    samples: "all"
    normalize: true 
    estimator: "direct"
- name: SemanticEntropy
  cfg:
    samples: "unique"
    normalize: false
    estimator: "sample"
- name: SemanticEntropy
  cfg:
    samples: "unique"
    normalize: false
    estimator: "direct"
- name: SemanticEntropy
  cfg:
    samples: "unique"
    normalize: true 
    estimator: "sample"
- name: SemanticEntropy
  cfg:
    samples: "unique"
    normalize: true 
    estimator: "direct"
- name: SentenceSAR
- name: CocoaMSP
- name: CocoaPPL
- name: CocoaMTE
- name: SemanticDensity
